FROM python:3.10-slim

WORKDIR /app

COPY . .

ENV VIRTUAL_ENV="/app/venv"
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN python3 -m venv /app/venv


# Upgrade pip and install dependencies

RUN /app/venv/bin/python -m ensurepip --upgrade
RUN /app/venv/bin/pip install --no-cache-dir --upgrade pip
RUN /app/venv/bin/pip install --no-cache-dir -r requirements.txt
CMD [ "/app/venv/bin/celery", "-A", "scheduler.celery_app", "beat", "--loglevel=info" ]